import Image from "next/image";
import { Github, Linkedin, Mail, ExternalLink, BriefcaseBusiness, GraduationCap, Code2, Cloud, BrainCircuit, ServerCog } from "lucide-react";

const work = [
 {title:"Apple Support Platform",subtitle:"Hybrid RAG · Production AI",desc:"A production-oriented AI support platform exploring hybrid retrieval with BM25 + vectors, metadata filtering, reciprocal rank fusion, reranking and evaluation.",tech:"Python · FastAPI · LangGraph · OpenSearch · RAG",href:"https://github.com/divyashankarkumar108/production-ai-app-unified-hybrid-rag",icon:BrainCircuit},
 {title:"AI Support with FastAPI",subtitle:"Backend · Applied AI",desc:"An AI support backend covering authentication, chat, document upload, streaming responses, middleware, database access, testing and production API patterns.",tech:"Python · FastAPI · APIs · AI",href:"https://github.com/divyashankarkumar108/ai-support-fastapi",icon:ServerCog},
 {title:"Distributed Systems & Cloud",subtitle:"Architecture · Engineering",desc:"Engineering explorations spanning microservices, event-driven systems, cloud-native architecture, caching, reliability and developer productivity.",tech:"AWS · Docker · Kubernetes · Kafka · Redis",href:"https://github.com/divyashankarkumar108",icon:Cloud}
];
const roles=[["Senior Software Engineer","Varo Bank","2020–2025"],["Senior Software Engineer","HelloSign, a Dropbox Company","2017–2020"],["Software Engineer","Gap Inc.","2016–2017"],["SDET","Green Dot Corporation","2015–2016"],["Senior QA Engineer","CyberSource, a Visa Company","2013–2014"],["Quality Assurance Analyst","Indian Institute of Management Bangalore","2007–2013"]];

export default function Home(){return <main className="bg-[#fbfaf7] text-[#263238]">
<header className="sticky top-0 z-50 border-b border-black/5 bg-[#fbfaf7]/90 backdrop-blur"><div className="container-x flex h-20 items-center justify-between"><a href="#top" className="text-xl font-extrabold tracking-tight">Divya Shankar Kumar</a><nav className="hidden gap-7 text-sm font-semibold md:flex">{["About","Work","Background","Skills","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} className="hover:text-[#c45d43]">{x}</a>)}</nav></div></header>
<section id="top" className="container-x grid min-h-[74vh] items-center gap-12 py-16 md:grid-cols-[.8fr_1.2fr]"><div className="mx-auto w-full max-w-sm"><div className="overflow-hidden rounded-full border-[10px] border-white shadow-xl"><Image src="/headshot.png" alt="Divya Shankar Kumar" width={900} height={900} priority className="aspect-square w-full object-cover"/></div></div><div><p className="eyebrow">Senior Software Engineer</p><h1 className="mt-4 text-5xl font-black leading-[1.04] tracking-[-.04em] md:text-7xl">I build scalable systems and practical AI products.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">10+ years building software across banking, payments, SaaS and enterprise platforms—with a focus on distributed systems, APIs, cloud architecture, reliability, developer productivity and Generative AI.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#work" className="rounded-full bg-[#c45d43] px-6 py-3 font-bold text-white">See my work</a><a href="/Divya-Shankar-Kumar-Resume.pdf" target="_blank" className="rounded-full border border-slate-300 px-6 py-3 font-bold">Résumé</a></div></div></section>
<section id="about" className="section bg-white"><div className="container-x grid gap-10 md:grid-cols-[.38fr_.62fr]"><div><p className="eyebrow">About Me</p><h2 className="mt-3 text-4xl font-black">Engineer. Architect. Builder.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>I’m a Senior Software Engineer with experience designing backend services, distributed integrations and cloud delivery systems. I enjoy turning complex requirements into reliable, maintainable software and reusable engineering patterns.</p><p>My recent work extends that foundation into production Generative AI: LLM integrations, RAG, orchestration and evaluation using FastAPI, LangGraph, LangChain and vector retrieval.</p></div></div></section>
<section id="work" className="section"><div className="container-x"><p className="eyebrow">My Work</p><h2 className="mt-3 text-4xl font-black md:text-5xl">Selected engineering projects</h2><div className="mt-12 space-y-8">{work.map((p,i)=>{const Icon=p.icon;return <article key={p.title} className="grid overflow-hidden rounded-[2rem] bg-white shadow-sm md:grid-cols-[.42fr_.58fr]"><div className="flex min-h-64 items-center justify-center bg-[#e8ece8] p-10"><div className="flex h-36 w-36 items-center justify-center rounded-full bg-[#fbfaf7] shadow-sm"><Icon size={58} strokeWidth={1.4}/></div></div><div className="p-8 md:p-10"><p className="eyebrow">{p.subtitle}</p><h3 className="mt-3 text-3xl font-black">{p.title}</h3><p className="mt-4 leading-7 text-slate-600"><b>Description:</b> {p.desc}</p><p className="mt-4 leading-7 text-slate-600"><b>Technologies:</b> {p.tech}</p><a href={p.href} target="_blank" className="mt-6 inline-flex items-center gap-2 font-extrabold text-[#c45d43]">View project <ExternalLink size={16}/></a></div></article>})}</div></div></section>
<section id="background" className="section bg-white"><div className="container-x"><p className="eyebrow">Background</p><div className="mt-10 grid gap-12 lg:grid-cols-2"><div><div className="flex items-center gap-3"><BriefcaseBusiness/><h2 className="text-3xl font-black">Experience</h2></div><div className="mt-7 space-y-6">{roles.map(r=><div key={r[0]+r[1]} className="border-b border-slate-200 pb-5"><h3 className="font-extrabold">{r[0]}</h3><p className="mt-1 text-slate-600">{r[1]} · {r[2]}</p></div>)}</div></div><div><div className="flex items-center gap-3"><GraduationCap/><h2 className="text-3xl font-black">Education & Certification</h2></div><div className="mt-7 rounded-3xl bg-[#fbfaf7] p-7"><h3 className="font-extrabold">AWS Certified AI Practitioner</h3><p className="mt-1 text-slate-600">Amazon Web Services · 2026–2029</p><hr className="my-6"/><h3 className="font-extrabold">Bachelor of Engineering, IT</h3><p className="mt-1 text-slate-600">Visvesvaraya Technological University</p></div></div></div></div></section>
<section id="skills" className="section"><div className="container-x"><div className="flex items-center gap-3"><Code2/><h2 className="text-4xl font-black">Skills</h2></div><div className="mt-8 flex flex-wrap gap-3">{["Java","Python","JavaScript","TypeScript","FastAPI","Microservices","REST APIs","GraphQL","gRPC","Distributed Systems","AWS","Lambda","ECS","EKS","Docker","Kubernetes","Kafka","RabbitMQ","Redis","Postgres","LangGraph","LangChain","PgVector","GitHub Actions","GitLab CI","Grafana","Datadog","Prometheus"].map(x=><span key={x} className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">{x}</span>)}</div></div></section>
<section id="contact" className="section bg-[#263238] text-white"><div className="container-x text-center"><p className="eyebrow !text-[#ef9c85]">Contact</p><h2 className="mt-4 text-4xl font-black md:text-5xl">Let’s build something meaningful.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">Connect with me about backend engineering, cloud architecture, distributed systems and applied AI.</p><div className="mt-8 flex justify-center gap-4"><a aria-label="Email" href="mailto:divyashankarkumar108@gmail.com" className="rounded-full bg-white p-3 text-[#263238]"><Mail/></a><a aria-label="GitHub" href="https://github.com/divyashankarkumar108" target="_blank" className="rounded-full bg-white p-3 text-[#263238]"><Github/></a><a aria-label="LinkedIn" href="https://www.linkedin.com/in/divyashankarkumar" target="_blank" className="rounded-full bg-white p-3 text-[#263238]"><Linkedin/></a></div></div></section>
<footer className="bg-[#263238] border-t border-white/10 py-7 text-center text-sm text-slate-400">© 2026 Divya Shankar Kumar · Built with Next.js + Tailwind CSS</footer></main>}